HARD_EPISODES = [
    {
        "id": "hard_001",
        "task_level": "hard",
        "post": {
            "content": "[AI SATIRE] Deepfake of politician dancing at press conference — clearly labeled comedy",
            "account_name": "TheDeshiOnion_Official",
            "account_age_days": 2190,
            "account_post_count": 1247,
            "platform": "Facebook",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": "RunwayML",
                "synthetic_confidence": 0.98,
                "labeled_as_ai": True,
                "label_visible_in_video": True,
                "label_text": "[AI SATIRE]",
            },
            "account_history": [
                "6 year old account, established Indian political satire publication",
                "All AI content consistently and clearly labeled",
                "Verified by Meta as an official satire page",
                "Zero policy violations in 6 years of operation",
                "Featured in journalism publications as a credible satire source",
            ],
            "policy": {
                "labeled_synthetic_media_exemption": "AI-generated content that is clearly and visibly labeled as satirical or fictional, and does not aim to deceive viewers, is explicitly permitted. Label must appear in the content itself. Established verified satire accounts with clean records qualify automatically.",
            },
        },
        "correct_ruling": "no_action",
        "correct_tools": ["query_policy", "query_account_history", "query_metadata"],
        "explanation": "Labeled satire from verified 6-year-old satire account = explicitly exempt. Surface signals scream remove but policy and account history say no_action. Agent must find the exemption.",
        "false_positive_risk": "very_high",
    },
    {
        "id": "hard_002",
        "task_level": "hard",
        "post": {
            "content": "Video of protest march in Manipur, crowds visible, police presence, posted by journalist",
            "account_name": "Riya_Correspondent_NE",
            "account_age_days": 1100,
            "account_post_count": 892,
            "platform": "Facebook",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": None,
                "synthetic_confidence": 0.09,
                "audio_anomaly_detected": True,
                "video_authentic": True,
                "labeled_as_ai": False,
                "device": "Canon EOS",
            },
            "account_history": [
                "3 year old verified journalist account",
                "Northeast India correspondent for a registered news outlet",
                "Content previously cited by national newspapers",
                "No violations, credibility score high",
                "Known for covering sensitive regional conflict zones",
            ],
            "policy": {
                "partially_synthetic_media": "Authentic video with anomalous audio requires escalation to human review.",
                "public_interest_exception": "Journalism from credible verified reporters covering genuine events is protected under public interest provisions.",
                "labeled_synthetic_media_exemption": "Does not apply here as content is not labeled as AI-generated.",
            },
        },
        "correct_ruling": "escalate",
        "correct_tools": ["query_metadata", "query_account_history", "query_policy"],
        "explanation": "Credible journalist, authentic video, but audio anomaly detected. Public interest content needs human review not removal. Tricky because most signals say no_action but audio anomaly forces escalate.",
        "false_positive_risk": "very_high",
    },
    {
        "id": "hard_003",
        "task_level": "hard",
        "post": {
            "content": "Video of famous actor promoting a cryptocurrency investment scheme, urgent tone",
            "account_name": "BollywoodBuzz_Official",
            "account_age_days": 1800,
            "account_post_count": 4200,
            "platform": "Instagram",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": "D-ID",
                "synthetic_confidence": 0.89,
                "labeled_as_ai": False,
                "upload_time": "03:22:00",
                "ip_location": "mismatched_to_account_history",
            },
            "account_history": [
                "5 year old entertainment news account",
                "Generally legitimate celebrity news coverage",
                "No prior violations in 5 years",
                "Account login location suddenly changed 3 days ago",
                "Unusual spike in posting frequency this week",
            ],
            "policy": {
                "synthetic_media_policy": "Unlabeled synthetic media depicting real people is prohibited.",
                "account_compromise_policy": "Accounts showing signs of unauthorized access should be flagged for security review alongside content action.",
            },
        },
        "correct_ruling": "remove",
        "correct_tools": ["query_metadata", "query_account_history", "query_policy"],
        "explanation": "High synthetic confidence + unlabeled + financial scam context + account compromise signals. Old legitimate account does NOT protect this — account appears hijacked. Remove content and flag account.",
        "false_positive_risk": "medium",
    },
    {
        "id": "hard_004",
        "task_level": "hard",
        "post": {
            "content": "Short comedy skit where creator plays an AI version of themselves, fully scripted and theatrical",
            "account_name": "StandupWithSuresh",
            "account_age_days": 980,
            "account_post_count": 310,
            "platform": "Instagram",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": "HeyGen",
                "synthetic_confidence": 0.76,
                "labeled_as_ai": True,
                "label_visible_in_video": True,
                "label_text": "This is an AI version of me — comedy only!",
                "creator_consent": True,
            },
            "account_history": [
                "2.7 year old verified comedian account",
                "Regular comedy content, growing audience",
                "Creator has previously posted about using AI tools creatively",
                "No violations, community favorite",
            ],
            "policy": {
                "labeled_synthetic_media_exemption": "AI-generated content that is clearly labeled as fictional or satirical is permitted. Creator consent to depict themselves using AI tools is an additional exemption qualifier.",
                "synthetic_media_policy": "Applies to non-consensual depictions. Does not apply when the depicted person is also the creator and has given consent.",
            },
        },
        "correct_ruling": "no_action",
        "correct_tools": ["query_policy", "query_metadata", "query_account_history"],
        "explanation": "Creator depicting themselves with AI + labeled + consent = explicitly exempt. High synthetic confidence is misleading here. Agent must read the policy carefully to find the consent exemption.",
        "false_positive_risk": "very_high",
    },
    {
        "id": "hard_005",
        "task_level": "hard",
        "post": {
            "content": "Video showing a government minister signing documents, shared as evidence in an ongoing court case",
            "account_name": "LegalWatchIN_Verified",
            "account_age_days": 1650,
            "account_post_count": 720,
            "platform": "Facebook",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": None,
                "synthetic_confidence": 0.14,
                "video_authentic": True,
                "audio_anomaly_detected": False,
                "labeled_as_ai": False,
                "linked_to_active_court_case": True,
            },
            "account_history": [
                "4.5 year old legal journalism account",
                "Covers court cases and legal proceedings",
                "Content cited in official court filings",
                "Verified by Meta as legal journalism page",
                "Zero violations in entire history",
            ],
            "policy": {
                "public_interest_exception": "Content submitted as evidence in legal proceedings or documenting genuine legal events from verified journalism sources is protected.",
                "legal_proceedings_policy": "Content linked to active court cases requires legal team review before any action is taken. Standard content policies are suspended pending legal review.",
            },
        },
        "correct_ruling": "escalate",
        "correct_tools": ["query_metadata", "query_account_history", "query_policy"],
        "explanation": "Authentic video + verified legal journalism + linked to active court case = mandatory escalation to legal team. Removing this could interfere with legal proceedings. Agent must find the legal proceedings policy.",
        "false_positive_risk": "very_high",
    },
]