MEDIUM_EPISODES = [
    {
        "id": "medium_001",
        "task_level": "medium",
        "post": {
            "content": "Leaked footage of state politician using offensive slurs at a private party",
            "account_name": "LeaksCentral_IN",
            "account_age_days": 180,
            "account_post_count": 89,
            "platform": "Facebook",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": None,
                "synthetic_confidence": 0.31,
                "audio_anomaly_detected": True,
                "video_authentic": True,
                "labeled_as_ai": False,
            },
            "account_history": [
                "6 month old account",
                "Mix of genuine leaks and some later-debunked stories",
                "2 prior policy warnings, no bans",
                "Some posts verified as real by independent journalists",
            ],
            "policy": {
                "partially_synthetic_media": "Content where video is authentic but audio may have been altered requires human review escalation — do not remove unilaterally.",
                "public_interest_exception": "Content revealing genuine wrongdoing by public figures may be exempt from removal pending human review.",
            },
        },
        "correct_ruling": "escalate",
        "correct_tools": ["query_metadata", "query_policy", "query_account_history"],
        "explanation": "Authentic video + anomalous audio + mixed account credibility = not clear cut, escalate to human",
        "false_positive_risk": "medium",
    },
    {
        "id": "medium_002",
        "task_level": "medium",
        "post": {
            "content": "Video of opposition leader appearing to endorse a rival party, widely shared",
            "account_name": "PoliticsWatchIN",
            "account_age_days": 730,
            "account_post_count": 1200,
            "platform": "Facebook",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": "FaceSwap Pro",
                "synthetic_confidence": 0.71,
                "upload_time": "18:45:00",
                "labeled_as_ai": False,
            },
            "account_history": [
                "2 year old political commentary account",
                "Mix of opinion pieces and shared news",
                "1 prior violation for misleading headline, resolved",
                "Has published verified accurate stories in the past",
            ],
            "policy": {
                "synthetic_media_policy": "Unlabeled synthetic media depicting real people in false scenarios is prohibited.",
                "political_content_policy": "Political content undergoes additional scrutiny, especially during election periods.",
            },
        },
        "correct_ruling": "remove",
        "correct_tools": ["query_metadata", "query_policy"],
        "explanation": "Synthetic confidence 0.71 with FaceSwap tool detected, political figure, unlabeled = remove. Account age does not override clear synthetic signal.",
        "false_positive_risk": "medium",
    },
    {
        "id": "medium_003",
        "task_level": "medium",
        "post": {
            "content": "Documentary-style video about working conditions in a garment factory, shared by activist group",
            "account_name": "LaborRightsIndia_Official",
            "account_age_days": 1460,
            "account_post_count": 560,
            "platform": "Facebook",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": None,
                "synthetic_confidence": 0.18,
                "audio_anomaly_detected": False,
                "video_authentic": True,
                "labeled_as_ai": False,
            },
            "account_history": [
                "4 year old registered NGO account",
                "Consistent labor rights advocacy content",
                "No prior violations",
                "Content has been cited by news outlets",
            ],
            "policy": {
                "public_interest_exception": "Content documenting genuine social or labor issues from credible advocacy accounts may be protected under public interest provisions.",
            },
        },
        "correct_ruling": "no_action",
        "correct_tools": ["query_metadata", "query_account_history"],
        "explanation": "Low synthetic confidence, authentic video, credible established NGO account. Public interest content. No action.",
        "false_positive_risk": "high",
    },
    {
        "id": "medium_004",
        "task_level": "medium",
        "post": {
            "content": "Video of a local police officer appearing to accept a bribe, posted by anonymous tipster",
            "account_name": "CitizenReport_Blr",
            "account_age_days": 45,
            "account_post_count": 12,
            "platform": "Facebook",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": None,
                "synthetic_confidence": 0.22,
                "video_authentic": True,
                "audio_anomaly_detected": False,
                "labeled_as_ai": False,
            },
            "account_history": [
                "45 day old account",
                "12 posts, mix of local news and personal content",
                "No violations",
                "Identity unverified but some posts corroborated by locals",
            ],
            "policy": {
                "public_interest_exception": "Content revealing potential wrongdoing by public officials may qualify for public interest protection, pending human review.",
                "partially_synthetic_media": "Low confidence synthetic scores still require verification before action.",
            },
        },
        "correct_ruling": "escalate",
        "correct_tools": ["query_metadata", "query_account_history", "query_policy"],
        "explanation": "Authentic video with low synthetic confidence, potential public interest content, newer account = escalate for human verification rather than remove",
        "false_positive_risk": "medium",
    },
    {
        "id": "medium_005",
        "task_level": "medium",
        "post": {
            "content": "News anchor appearing to break down crying on air about a government policy, clip going viral",
            "account_name": "MediaBiteIN",
            "account_age_days": 600,
            "account_post_count": 340,
            "platform": "Instagram",
        },
        "available_tools": {
            "metadata": {
                "video_creation_tool": "ElevenLabs",
                "synthetic_confidence": 0.58,
                "audio_anomaly_detected": True,
                "video_authentic": True,
                "labeled_as_ai": False,
            },
            "account_history": [
                "Media clip aggregator account, 600 days old",
                "Generally reposts real news clips",
                "1 prior warning for out-of-context clipping",
                "No synthetic media violations before",
            ],
            "policy": {
                "partially_synthetic_media": "Authentic video with synthetic audio requires escalation, not automatic removal.",
                "synthetic_media_policy": "Unlabeled synthetic audio overlaid on real video still constitutes a synthetic media violation.",
            },
        },
        "correct_ruling": "escalate",
        "correct_tools": ["query_metadata", "query_policy"],
        "explanation": "Real video + ElevenLabs audio tool detected + audio anomaly = synthetic audio on real video. Policy says escalate not remove.",
        "false_positive_risk": "medium",
    },
]